config/routes.rb
Reddit::Application.routes.draw do

  resources :users do
    resources :stories
  end

  #resources :sessions, only: [:new, :create, :destroy]
    get "/login", to: "session#new"
    post "/session", to: "session#create"
    delete "/session", to: "session#destroy"

    root "welcome#index"

end

app/models/story.rb
class Story < ActiveRecord::Base
  belongs_to :user
  validates :url, presence: true, uniqueness: true
  validates :user_id, presence: true

end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :stories
  validates :username, presence: true, uniqueness: true
  validates :email, presence: true, uniqueness: true
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def current_user
    @current_user ||= User.find_by(id: session[:user_id] )
  end

  def logged_in?
    current_user.present?
  end

  helper_method :current_user, :logged_in?
end

app/controllers/session_controller.rb
class SessionController < ApplicationController

  def new
    render(:new)
  end

  def create
    # find if any user has that email
    user = User.find_by(email: params[:email])
    
    # if that user exists and it has a password that
    # was sent
    if user && ( user.authenticate(params[:password]) )
      
      # save the user_id in the session hash
      session[:user_id] = user.id

      # and redirect to that user's home page
      redirect_to( user_path(user) )
    else

      # the email/password is wrong!
      @message = "This email and password combination does not exist."
      render(:new)
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end

end

app/controllers/stories_controller.rb
require 'pry'
class StoriesController < ApplicationController

  def new
    @user = User.find(params[:user_id])
    @story = Story.new
  end

  def create
    @user = User.find(params[:user_id])
    @story = @user.stories.new(url: params[:story][:url])
    if @story.save

      redirect_to ("/users/#{params[:user_id]}")
    else
      render(:new)
    end
  end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  # before_action :load_user, only: [:show, :edit, :update, :destroy]
  before_action :authenticate, :authorize, only: [:edit, :update]
  
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      session[:user_id] = @user.id
      redirect_to user_path(@user)
    else
      render(:new)
    end
  end

  def show
    @user = User.find(params[:id])
  end


private 
  def user_params
    params.require(:user).permit(:username, :email, :password, :password_confirmation)
  end
end

def authorize
  unless current_user == @user
    redirect_to login_path
  end
end

def authenticate
  unless logged_in?
    redirect_to login_path
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index
    
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Reddit</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/session/new.html.erb
<h2>Login below!</h2>

<div class="form">
<% unless @message.nil? %>
  <div id="errors">
    <h3>Errors!</h3>
    <ul>
      <li><em><%= @message %></em></li>
    </ul>
  </div>
<% end %>

<%= form_tag "/session" do %>
  <%= label_tag :email %>
  <%= email_field_tag :email %>
  <%= label_tag :password %>
  <%= password_field_tag :password %>
  <br>
  <%= submit_tag "Log in!" %>
<% end %>
</div>

app/views/stories/new.html.erb
<%= form_for [@user, @story] do |f|%>
  <%= f.label :url %>
  <%= f.text_field :url %><br />

  <%= f.submit %>
<% end %>

app/views/users/_form.html.erb
<%= form_for @user do |f|%>
  <%= f.label :username %>
  <%= f.text_field :username %><br />
  <%= f.label :email %>
  <%= f.email_field :email %><br />
  <%= f.label :password %>
  <%= f.password_field :password %><br />
  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation %><br />
  <%= f.submit @user.id.nil? ? "Signup" : "Save Changes" %>
<% end %>

app/views/users/new.html.erb
<%= render "form" %>

app/views/users/show.html.erb
<%= @user.username %>
<%= link_to "add story", new_user_story_path(@user) %>

app/views/welcome/index.html.erb
<%= link_to "Signup", new_user_path %>
<%= link_to "login", "/login" %>